language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

# @see https://docs.travis-ci.com/user/notifications/#Changing-notification-frequency
notifications:
  webhooks:
    urls:
      - https://ci-lights-server.herokuapp.com/
    on_success: change # default: always
    on_failure: always # default: always
    on_start: always   # default: never
    on_cancel: always # default: always
    on_error: always # default: always

deploy:
  provider: heroku
  api_key: # @see https://docs.travis-ci.com/user/encryption-keys/
    secure: Adv4uf+pxQP9f3bHY0bQc5YfpLiUGUuCL4M6fmO9ApA+k/DJRAc+CQQsJeCBFRgdwB/zudTuu9r5gDsGxNy/DkJ1HodAFaNcnCZPTx+jehHQaQloW/rxW5lVarqEZyvwCFLxAlAXPyJRvNPNXu0uVID9aBPNiaaKJ/WBM+c1sITsnPn0ampX0HcdhG1WRPEPpuvZbnLxYVOe80Qfk6otrqHJyrFKFfTNtuafPHrpXxb2SW46yjPkFUok+motnOGSeJ17TrOsKaY5/J2GTZkYxwIF+gQzPodOKCyoVKhgmmXu9AW1nW/hTKUP4VVPQDLFJXWmVqltlT/Uz38FpAr+tuxzxIDWc+w42LaosdSdxM5YC1rpYxuDSz+QKQQUv0n1bm4qxTb+d4o8Fg2jZwxUrjJ3JXGZ8tbranl0bolXK2ZkRXcMFiFYxIkWLv8vZqq0arPb91Ze4UOuBgVgEBP4kc/K3cS/jl3bFMsx8XMDah5OTj8trxO8lwqSD9PF2DG/JbGVkcS/0fyLFvSs3kg5kQpZT2RJpZp7qDiEIYwzQXNZY+DH7Fi/hUFW1nHt74AMfM4xgYm0akB4+43CdA8MVNNi7NTu8muG7v0kFavGcmBh63vsQ7KJHFhNRYZcwQFo97RiKd1ldlcyndb6ODKyrkDCvGIC5yWDW421haJXVZo=
