language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

# @see https://docs.travis-ci.com/user/notifications/#Changing-notification-frequency
notifications:
  webhooks:
    urls:
      - https://ci-lights-server.herokuapp.com/notify
    on_success: change # default: always
    on_failure: always # default: always
    on_start: always   # default: never
    on_cancel: always # default: always
    on_error: always # default: always

deploy:
  provider: heroku
  api_key: # @see https://docs.travis-ci.com/user/encryption-keys/
    secure: ONlOz5IuYsLHuM+fy8ZAWMqFurFQiM81Ln17aeefaKYqQmzyC9PCrajb3pDs9Jrmyo0ZVZGQDpN95epGEjYWN4nMLMlsZt/CxYt6nw2kswSprTPcMR8R/xV83uqG7lh0bK7h+VmuOYrKi7j7YoJXh3mlay2iFeqBifDevMw2g3qZeBsbhXBO99KmAH8M6abkwxQlNGs3WgF456LFmR8NVkb4LxIEEA/j7eiiKMLsb82/GkpGSAt7A8ZETz/8Ur0hx4C0zlcnJP+HlXdQOgbmeP1+8TrLopWrpz/RbjdgzItEfob6VP/tRmsj+AEQ7AIfs5kOefN91sN33qXy1RTvhv1LZ8Ll7pdqsNHVvIU+xb7Sh0g+EX2X1S8KagD7yewyvUq9XZQNhQ8jJUcbYFWlfSzvVPcKlaB6uISihO1j4yplrLDLnO6sguobzKE3R1o6/JAtycssl7x+JDZ5wb+LtMyl+i7ZiU9mcPs++h18jRbWSxSs7SxmPovbs1/9i9YSViErAeMIAoE5t6th3ahiij0fnPOr+LvuVH8369tTezOy4Z0NDo7RJn/QEe6u4n/E9d8X9Rhy2dWi+iUfPq5JGhntKzimV+EPbvRD00Zy3LnFd9Ht9teT24OEY6zYS5iJ7gpF2MHUFCvJmLG103j7TbEhoaBRH1Q+dEje4Cu8iDQ=
  app: ci-lights-server
  on:
    repo: ci-lights/server
